vim.keymap.set('n', "<leader>ve", ":e ~/.config/nvim/init.lua<CR>")
vim.keymap.set('n', "<C-b>", ":NvimTreeFindFileToggle<CR>")
vim.keymap.set('n', '<C-c>', ':q<CR>')
vim.keymap.set('n', '<C-s>', ':w<CR>')
vim.keymap.set('i', "<C-s>", "<Esc>:wa<CR>")
vim.keymap.set('n', '<C-e>', ':Telescope buffers<CR>')
vim.keymap.set('n', '<C-p>', ':Telescope find_files<CR>')
vim.keymap.set('n', '<C-f>', ':Format<CR>')
vim.keymap.set('n', "<space>s", ":Telescope lsp_workspace_symbols<CR>")
vim.keymap.set('n', "<leader>f", ":Telescope live_grep<CR>")
vim.keymap.set('n', "gr", ":Telescope lsp_references<CR>")
vim.keymap.set('n', "<leader>a", vim.lsp.buf.code_action)
vim.keymap.set('n', "<C-O>", ":Telescope lsp_document_symbols<CR>")
vim.keymap.set('n', "L", vim.diagnostic.open_float)
vim.keymap.set('n', "tt", ":hi Normal guibg=NONE ctermbg=NONE<CR>")
vim.keymap.set('n', "<leader>g", ":Neogit<CR>")
vim.keymap.set('v', "<", "<gv")
vim.keymap.set('v', ">", ">gv")

vim.keymap.set('n', "<leader>dt", function() require("dapui").toggle() end)
-- vim.keymap.set('n', '<F8>', require("dap").toggle_breakpoint())
-- vim.keymap.set('n', '<F9>', require("dap").continue, { noremap = true })
-- vim.keymap.set('n', '<F10>', require("dap").step_over, { noremap = true })
-- vim.keymap.set('n', '<S-F10>', require("dap").step_into, { noremap = true })
-- vim.keymap.set('n', '<F12>', require("dap.ui.widgets").hover, { noremap = true })
--

vim.keymap.set('n', '<F9>', function() require('dap').continue() end)
vim.keymap.set('n', '<F8>', function() require('dap').step_over() end)
vim.keymap.set('n', '<F7>', function() require('dap').step_into() end)
vim.keymap.set('n', '<F12>', function() require('dap').step_out() end)
vim.keymap.set('n', '<Leader>b', function() require('dap').toggle_breakpoint() end)
vim.keymap.set('n', '<Leader>dr', function() require('dap').repl.open() end)

