vim .opt.smartindent = true
vim.opt.termguicolors = true
vim.opt.relativenumber = true
vim.opt.mouse = 'a'
vim.opt.clipboard = 'unnamedplus'
vim.opt.tabstop = 2
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.scrolloff = 8
vim.opt.hlsearch = false
